Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('',include('Web_blog.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Blog/Web_blog/urls.py
from unicodedata import name
from django.urls import path
from Web_blog import views
from django.contrib.auth.views import LoginView

urlpatterns = [ 
    path('',views.home, name= 'home'),
    path('login',views.loginUser, name= 'login'),
    path('register',views.register, name= 'register'),
    path('form' ,views.form, name= 'form'),
    path('logout' , views.logoutUser, name='logout' ),
    path('about/' , views.about, name='about'),
    path('center/' , views.center, name='center'),
    path('post_comment/<id>', views.comments, name='comments'),
    path('post_like/<id>', views.likes, name='likes'),
    path('contact/', views.contact, name= 'contact'),
    path('detailpage/<id>', views.detailpages, name='detailpages'),
    path('profile/<id>',views.profile, name='profile' ),
    path('allpost/' ,views.allpost, name= 'allpost'),
    
]


  

Blog/Web_blog/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User


class Bloggers(models.Model):
    phone = models.CharField(max_length=30)
    account_num = models.CharField(max_length=100)
    user = models.OneToOneField(User , models.CASCADE, null=True)
    author = models.ImageField(upload_to='blogger/' , blank=True)
  
    
    def __str__(self):
        return self.user.username
    
class Post(models.Model):
    text_post = models.TextField()
    title = models.CharField(max_length=100, null=True)
    post_date = models.DateTimeField(default=datetime.now, blank=True)
    creator = models.ForeignKey(Bloggers , models.DO_NOTHING)
    post_image = models.ImageField(upload_to='post/', blank=True)
    likes = models.ManyToManyField(Bloggers, related_name='like_post')
    
    def __str__(self):
            return self.title


class Comments(models.Model):
    coment_text = models.TextField(max_length=200)
    post = models.ForeignKey(Post , models.CASCADE)
    creator = models.ForeignKey(Bloggers , models.CASCADE)
  
    def __str__(self):
            return 'comment'


class Contact(models.Model):
   email = models.CharField(max_length=50) 
   phone = models.CharField(max_length=20)

   def __str__(self):
            return 'contact'

Blog/Web_blog/views.py
from datetime import datetime
from xml.etree.ElementTree import Comment
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages

from .models import Comments,  Post, Bloggers

def loginUser(request):
    if request.method == "POST":
        username = request.POST["username"]
        
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
            ...
        else:
            # Return an 'invalid login' error message.
            ...

    return render(request,'Login.html')

def home(request):
    all_posts = Post.objects.all()
    all_bloggers = Bloggers.objects.all()
    return render(request,'index2.html', {'posts':all_posts, 'bloggers':all_bloggers})


# Create your views here.
def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['passwordRepeat']
        if password == password2:
            if User.objects.filter(username=username).exists():
               messages.error(request, 'That username is taken')
               return redirect('register')
            else:
                user = User(username=username,email=email, first_name=first_name, last_name=last_name)
                user.set_password(password)
                user.save()
                blogger = Bloggers.objects.create(phone='000000',account_num='xxxxxxx',user=user)

                return redirect('login')
    return render(request, 'Register.html')


#create your view form here.

def form(request):
    if request.method == 'POST':
        textpost = request.POST['text_post']
        post= request.POST['posttitle']
        img= request.FILES['postfile']
        posts = Post.objects.create(text_post=textpost,post_date=datetime.now(),creator=request.user.bloggers, title=post, post_image= img)
         
        return redirect('home')
    return render(request, 'post.html')
    
#creating a logout

def logoutUser(request):
    logout(request)
    return redirect('home')

#create the about page

def about(request):

    return render(request, 'about.html')

#create your help center page

def center(request):
    
    return render(request, 'center.html')

#create your comment views
#retrive data from the database
def comments(request, id):
    if request.method == "POST":
        comments= request.POST['comment']
        post_comment=Comments.objects.create(coment_text=comments,post_id=id,creator_id=request.user.bloggers.id )
        return redirect('detailpages' ,id)


def likes(request, id):
    post_to_like = Post.objects.get(id=id)
    post_to_like.likes.add(request.user.bloggers)
    return redirect('detailpages' ,id)

#create your contact views here

def contact(request):

    return render(request, 'contact.html')

#create your detailpage views
#retrive data from the database
def detailpages(request, id):
    post_details = Post.objects.get(id=id)
    
    return render(request, 'detailpage.html', {'post': post_details})

#create your profile views here
def profile(request,id):
    thisuser= User.objects.get(id=id)
    all_userpost = thisuser.bloggers.post_set.all()
    #Get the total number of likes
    total_likes=0
    for post in all_userpost:
        total_likes += post.likes.count()



    return render(request, 'profile.html',{'thisuser': thisuser, 't_likes':total_likes})

#create your allpost views here
def allpost(request ):
    blogposts=Post.objects.all()


    return render(request, 'allpost.html',{'posts': blogposts})


    
    


        
        

Blog/Web_blog/templates/contact.html
{% extends 'index2.html' %}

{% block style %} 
 <style>
    .my-nav{
      background-color:gray !important;
    }
 </style>
{% endblock style %}


{% block content %}
<hr style="width: 80px ; color: blue; height: 100px;">
   
<div class="row" style="margin-right: -500px;margin-right: -229px;">
    <div class="col-md-4 col-sm-6 col-lg-4 mt-4" >
        <div class="post-box">
            <div class="post-thumb">
             {% if post.post_image 
              <h5 class="card-title" style="margin: 5px;">Contact Our Theme</h5>
              <img src="../../media/post/images3.jpg" style="margin: 50px;" />
              <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
              <a href="home" class="btn btn-primary" style="margin: 5px;">Go somewhere</a>
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-6 col-lg-4 mt-4" >
        <div class="post-box">
            <div class="post-thumb">
             <h5 class="card-title" style="margin: 5px;">Contact Our Theme</h5>
             <img src="../../media/post/images2_SnS61OH.jpg" style="margin: 50px;" />
             <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
             <a href="home" class="btn btn-primary" style="margin: 5px;">Go somewhere</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

Blog/Web_blog/templates/detailpage.html
{% extends 'index2.html' %}


{% block style %} 
<style>
    .my-nav{
      background-color:burlywood !important;
    }
 </style>
{% endblock style %}
                     
{% block content %}
<div class="container" style="margin: 220px;">
<!-- Page content-->
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-8">
            <!-- Post content-->
            <article>
                <!-- Preview image figure-->
                <figure class="mb-4"><img class="img-fluid rounded" src="{{post.post_image.url}}" alt="..." /></figure>
                <!-- Post content-->
                <span>{{post.comments_set.count}}</span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-dots-fill" viewBox="0 0 16 16">
                    <path d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM5 8a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                  </svg>
                  <span>{{post.likes.count}}</span>
                  <a href="{%  url 'likes'  id=post.id %}"><button type="button" class="btn btn-outline-danger"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                  <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                  </svg></button></a>
                <section class="mb-5">
                    <h2> {{post.title}} </h2>
                    <h5>Title description, {{post.post_date}}</h5>
                    <p>{{post.post_text}}</p>
                </section>
            </article>
             <!-- Comments section-->
             <section class="mb-5">
                <div class="card bg-light">
                    <div class="card-body">

                       <!-- Comment -->
                       {% for comment in post.comments_set.all %}

                       <div class="d-flex mb-4">
                        <!-- Parent comment-->
                        <div class="flex-shrink-0">
                            <img class="rounded-circle" src="{{comment.creator.author.post.url}}" alt="..."  width='50' height='50'/></div>
                        <div class="ms-3">
                            <div class="fw-bold">{{comment.creator}}  </div>
                            {{comment.coment_text}}
                        </div>
                    </div>
                    <!-- Single comment-->
                    {% endfor %}
                    {% if user.is_authenticated %}
                        <form method="POST" action="{% url 'comments' id=post.id %}">
                        {% csrf_token %}
                        <input type="text" name="comment" placeholder="Comments">
                        <button type="submit" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-dots-fill" viewBox="0 0 16 16">
                            <path d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM5 8a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                          </svg></button>
                          </form>
                          {% endif %}     
   
                </div>
            </div>
        </section>
    </div>
    <!-- Side widgets-->
    <div class="col-lg-4">
        <!-- Search widget-->
        <div class="card mb-4 ">
            <div class="card-header">Search</div>
            <div class="card-body">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                    <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                </div>
            </div>
        </div>
        <div class="card mb-4 ">
            <h2>Author informations</h2><br>
            <h2>{{post.creator.user.username}}</h2>
            
            <div class="col-md-8 col-sm-8 col-lg-8 mt-2" >
                <div class="post-box">
                    <div class="post-thumb">
                        {% if post.creator.author %}
                        <img src="{{post.creator.author.url}}" class="rounded" >
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

Blog/Web_blog/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<title>Blog Website</title>
  <style>
    body {
  font-family: Arial;
  padding: 20px;
  background: #f1f1f1;
    }

    .container{
      width: 100%;
      height:50vh;
      background-image: url('../../media/post/citys.jpg');
      background-size: cover;
      background-position: center;
      background-repeat: no-repeat;
      padding-left: 8%;
      padding-right: 8%;
      box-sizing: border-box;
      

    }

    /* Header/Blog Title */
    .header {
      height: 15%;
      display: flex;
      align-items: center;
      overflow: hidden;
      position: relative;
    }

    .navbar{
      text-align: center;
      flex: 1;
    }

    .navbar a{
      padding: 6px 20px;
      text-decoration: none;
      color: purple;
      margin-left: 20px;
      font-size: 20px;
      font-weight: bold;
    }

    .content{
      text-align: center;
      margin-top: 1%;
    }

    .content h1{
      color: blue;
    }
    /* Create two unequal columns that floats next to each other */
    /* Left column */
    .leftcolumn {
      float: left;
      width: 70%;
    }

    /* Right column */
    .rightcolumn {
      float: left;
      width: 25%;
      padding-left: 20px;
    }

    /* Fake image */
    .fakeimg {
      background-color: #aaa;
      width: 100%;
      padding: 20px;
    }

    /* Add a card effect for articles */
    .card {
      background-color:white;
      padding: 2px;
      margin-top: 20px;
      
    }
    /* Clear floats after the columns */
    .row:after {
      content: "";
      display: table;
      clear: both;
    }
    /* Footer */
    .footer {
      background-image: url('../../media/post/cities3.jpg');
      padding: 20px;
      text-align: center;
      
      margin-top: 20px;
    }

    /* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
    @media screen and (max-width: 800px) {
      .leftcolumn, .rightcolumn {
        width: 100%;
        padding: 0;
      }
    }



    h2{
      color: orange;
      
    }
    .logo{
      cursor: pointer;
    width: 50px;
    }









  </style>
</head>
<body> 
  <div class="container">
    <div class="header">
      <img src="../../media/blogger/logo.webp" class="logo">
      <div class="navbar">
        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        <a class="nav-link" href="{% url 'about' %}">About</a>
        <a class="nav-link" href="#">Contact</a>
        <a class="nav-link" href="{% url 'center' %}">Help Center</a>
        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'form' %}"><i class="fa fa-globe fa-3x"></i>Make a post</a>
        <a class="nav-link" href="#">Welcome {{ user.username}}</a>
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'login' %}">Login</a>
        <a class="nav-link" href="{% url 'register' %}">Register</a>
        {% endif %}
      </div>
      <div class="content">
        <h1>Talkers</h1>
      </div>
    </div>
  </div>
      <div class="row">
        <div class="leftcolumn" >
          {% for post in posts %}
          <div class="card">
            <h2> {{post.title}} </h2>
            <h5>Title description, {{post.post_date}}</h5>
            <div style="height: 100%; width: 100%;">
              {% if post.post_image %}
              <img src="{{post.post_image.url}}" style=" height: 100%; width: 100%;">
              {% endif %}
            </div>
            {% if user.is_authenticated %}
            <form method="POST" action="{% url 'comments' id=post.id %}">
            {% csrf_token %}
            <input type="text" name="comment" placeholder="Comments">
            {% for comment in post.comments_set.all %}
            <div>
              <span> <img src=" {{comment.creator.blogger.url}}  " class="rounded-circle" style="width: 0%;" alt="">{{comment.creator}} : {{comment.coment_text}}  </span>
            </div>
            {% endfor %}
           <span>{{post.comments_set.count}}</span>
            <button type="submit" ><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-dots-fill" viewBox="0 0 16 16">
              <path d="M16 8c0 3.866-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.584.296-1.925.864-4.181 1.234-.2.032-.352-.176-.273-.362.354-.836.674-1.95.77-2.966C.744 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7zM5 8a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg></button>
           <span>{{post.likes.count}}</span>
            <a href="{%  url 'likes'  id=post.id %}"><button type="button"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
              <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
            </svg></button></a>
           
          </form>
          </div>
          {% endfor %}
        </div>
        <div class="rightcolumn">
          <div class="card">
            <h2>{{user.username}}</h2>
            <h5>About Blogger, {{post.post_date}}</h5>
            {% if user.bloggers.author %}
            <img src="{{user.bloggers.author.url}}" style="height:320px; width: 100%;">
            {% endif %}
            <p>some text...</p>
          </div>
          <div class="card">
            <h2>{{user.username}}</h2>
            <h5>Blogger Bio, {{post.post_date}}</h5>
            {% if user.bloggers.author %}
            <img src="{{user.bloggers.author.url}}" style="height:320px; width: 100%;">
            {% endif %}
            <p>some text...</p>
          </div>
        </div>
      <div class="footer">
        <div class="row">
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Contact Our Theme</h5>
                <img src="../../media/post/images3.jpg" style="border-radius: 50%" />
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Contact Our Theme</h5>
                <img src="../../media/post/images2_SnS61OH.jpg" style="border-radius: 50%" />
                <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                <a href="#" class="btn btn-primary">Go somewhere</a>
              </div>
            </div>
          </div>
        </div>


      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

</body>

Blog/Web_blog/templates/profile.html
{% extends 'index2.html' %}


{% block style %} 
 <style>
    .my-nav{
      background-color:gray !important;
    }

    @import url("https://fonts.googleapis.com/css2?family=Poppins:weight@100;200;300;400;500;600;700;800&display=swap");

    body{
        background-color:#545454;
        font-family: "Poppins", sans-serif;
        font-weight: 300;
  }

  
    .card{

        width: 380px;
        border: none;
        border-radius: 15px;
        padding: 8px;
        background-color: #fff;
        position: relative;
        height: 370px;
    }

    .upper{

        height: 100px;

    }

    .upper img{

        width: 100%;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;

    }

    .user{
        position: relative;
    }

    .profile img{

        
        height: 80px;
        width: 80px;
        margin-top:2px;

       
    }

    .profile{

        position: absolute;
        top:-50px;
        left: 38%;
        height: 90px;
        width: 90px;
        border:3px solid #fff;

        border-radius: 50%;

    }
       
    .follow{

        border-radius: 15px;
        padding-left: 20px;
        padding-right: 20px;
        height: 35px;
    }

    .stats span{

        font-size: 29px;
    }



 </style>
{% endblock style %}
{% block content %}
<div class="container" style="margin: 98px;">
    <div class="container d-flex justify-content-center align-items-center">
             
    
        <div class="card">
    
         <div class="upper">
    
           <img src="https://i.imgur.com/Qtrsrk5.jpg" class="img-fluid">
           
         </div>
    
         <div class="user text-align-items-center">
    
           <div class="profile">
            {% if thisuser.bloggers.author %}
             <img src="{{thisuser.bloggers.author.url}}" class="rounded-circle" width="80">
             {% endif %}
           </div>
    
         </div>
    
    
         <div class="mt-5 text-center">
    
           <h4>{{thisuser.username}}</h4>
           <h4>{{thisuser.profile}}</h4>
           
    
    
           <div class="d-flex justify-content-between align-items-center mt-4 px-4">
    
             <div class="stats">
               <h6 class="mb-0">Total Posts</h6>
               <span>{{thisuser.bloggers.post_set.count}}</span>
             </div>
    
    
             <div class="stats">
               <h6 class="mb-0">Total Likes</h6>
               <span>{{t_likes}}</span>
             </div>
    
    
             <div class="stats">
               <h6 class="mb-0">Total Comments</h6>
               <span>{{thisuser.bloggers.comments_set.count}}</span>
    
             </div>
             
           </div>
           
         </div>
          
        </div>
        
      </div>
      <h2 style="margin: 30px 450px; text-decoration:underline">Check your posts</h2>
      <div class="row">
        {% for post in thisuser.bloggers.post_set.all %}
            <div class="col-md-4 col-sm-6 col-lg-4 mt-4" >
                <div class="post-box">
                    <div class="post-thumb">
                        {% if post.post_image %}
                        <img src="{{post.post_image.url}}" class="" alt="post-img" height="300"/>
                        {% else %}
                        <img src="https://image.shutterstock.com/image-vector/no-image-vector-isolated-on-260nw-1481369594.jpg" class="img-fluid" alt="post-img" />
                        {% endif %}
                        <div class="date">
                            <span>25</span>
                            <span>July</span>
                        </div>
                    </div>
                    <div class="post-info">
                        <h4>{{post.title}}  </h4>
                        <ul>
                            <li>by {{post.creator.user.username}} </li>
                            <li>{{post.post_date}} </li>
                            <li><a href="{% url 'detailpages' id=post.id %} ">Click For More Info<b><span>{{post.comments_set.count}}</span>
                                Comments</b></a></li>
                        </ul>
                        
                        <span>{{post.likes.count}}</span>
                        <a href="{%  url 'likes'  id=post.id %}"><button type="button" class="btn btn-outline-danger"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                        <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                        </svg></button></a>
                        <p>{{post.text_post | truncatewords:8}} .</p>
                    </div>
                </div>
            </div>
            {% endfor %}
    </div>

</div>

{% endblock %}